services:
  app:
    build:
      context: ..
      dockerfile: deployments/app/Dockerfile
    container_name: apirest
    image: apirest:latest
    volumes:
      - ../config.yml:/app/config.yml
    ports:
      - "8080:8080"
    networks:
      - main_network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: apirest_pg
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: apirest
    volumes:
      - apirest_data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - main_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d apirest" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  apirest_data:

networks:
  main_network:
    driver: bridge