services:
  app:
    build:
      context: ..
      dockerfile: ./deployments/app/Dockerfile
    container_name: go_app
    platform: linux/amd64
    depends_on:
      - db:
            condition: service_healthy
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname?sslmode=disable
    ports:
      - "8080:8080" # или любой другой порт, который использует ваше приложение
    networks:
      - network

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - network
    # healthcheck. pg_isready

volumes:
  postgres_data:

networks:
  network:
    driver: bridge